[package]
name = "tafkars"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["derivator <derivator@users.noreply.github.com>"]
description = "The API formerly known as..."

[dependencies]
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
